---
- hosts: all
  become: true
  tasks:
    - name: "Update etc/hosts"
      lineinfile:
        path: /etc/hosts
        line: '{{ item }}'
      with_items:
        - '192.168.100.70 node-1 zabbix-svr.redhatmm.local zabbix-svr'
        - '192.168.100.71 node-2 zabbix-db.redhatmm.local zabbix-db'
        - '192.168.100.73 node-3 zabbix-proxy.redhatmm.local zabbix-proxy'

    - name: Install basic packages
      yum:
        name:
          - ca-certificates
          - curl
          - python3
          - python3-pip
        state: present
        update_cache: True

    - name: "Installing Python module"
      pip:
        name: netaddr

    - name: Set authorized key taken from file
      authorized_key:
        user: vagrant
        state: present
        key: "{{ lookup('file', 'id_rsa.pub') }}"

    - name: Set timezone to Asia/Yangon
      community.general.timezone:
        name: Asia/Yangon
